CREATE TABLE app_user (
    id UUID PRIMARY KEY,
    username VARCHAR(100) NOT NULL,
    normalized_username VARCHAR(100) NOT NULL UNIQUE,
    display_name VARCHAR(200) NOT NULL,
    password_hash VARCHAR(100) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    credentials_changed_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT app_user_status_check CHECK (status IN ('ACTIVE', 'LOCKED', 'DISABLED'))
);

CREATE TABLE app_role (
    id UUID PRIMARY KEY,
    code VARCHAR(50) NOT NULL UNIQUE,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(500) NOT NULL,
    system_role BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE app_permission (
    id UUID PRIMARY KEY,
    code VARCHAR(100) NOT NULL UNIQUE,
    description VARCHAR(500) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE app_user_role (
    user_id UUID NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
    role_id UUID NOT NULL REFERENCES app_role(id) ON DELETE RESTRICT,
    assigned_by UUID REFERENCES app_user(id) ON DELETE SET NULL,
    assigned_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (user_id, role_id)
);

CREATE TABLE app_role_permission (
    role_id UUID NOT NULL REFERENCES app_role(id) ON DELETE CASCADE,
    permission_id UUID NOT NULL REFERENCES app_permission(id) ON DELETE CASCADE,
    PRIMARY KEY (role_id, permission_id)
);

CREATE TABLE user_session (
    id UUID PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
    token_hash CHAR(64) NOT NULL UNIQUE,
    client_ip_hash CHAR(64) NOT NULL,
    user_agent VARCHAR(512),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_seen_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMPTZ NOT NULL,
    revoked_at TIMESTAMPTZ,
    CONSTRAINT user_session_expiry_check CHECK (expires_at > created_at)
);

CREATE INDEX user_session_active_user_idx
    ON user_session (user_id, expires_at)
    WHERE revoked_at IS NULL;

CREATE TABLE password_reset_token (
    id UUID PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
    token_hash CHAR(64) NOT NULL UNIQUE,
    requested_ip_hash CHAR(64) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMPTZ NOT NULL,
    consumed_at TIMESTAMPTZ,
    CONSTRAINT password_reset_expiry_check CHECK (expires_at > created_at)
);

CREATE INDEX password_reset_active_user_idx
    ON password_reset_token (user_id, expires_at)
    WHERE consumed_at IS NULL;

CREATE TABLE authentication_attempt (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    principal_hash CHAR(64) NOT NULL,
    client_ip_hash CHAR(64) NOT NULL,
    succeeded BOOLEAN NOT NULL,
    attempted_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX authentication_attempt_rate_limit_idx
    ON authentication_attempt (principal_hash, client_ip_hash, attempted_at DESC);

CREATE TABLE audit_event (
    id UUID PRIMARY KEY,
    actor_user_id UUID REFERENCES app_user(id) ON DELETE SET NULL,
    action VARCHAR(100) NOT NULL,
    target_type VARCHAR(100),
    target_id VARCHAR(200),
    outcome VARCHAR(20) NOT NULL,
    correlation_id VARCHAR(128),
    detail JSONB NOT NULL DEFAULT '{}'::jsonb,
    occurred_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT audit_event_outcome_check CHECK (outcome IN ('SUCCESS', 'FAILURE', 'DENIED'))
);

CREATE INDEX audit_event_actor_time_idx ON audit_event (actor_user_id, occurred_at DESC);
CREATE INDEX audit_event_action_time_idx ON audit_event (action, occurred_at DESC);

INSERT INTO app_role (id, code, name, description) VALUES
    ('00000000-0000-0000-0000-000000000001', 'SYSTEM_ADMIN', 'System administrator', 'Full platform administration.'),
    ('00000000-0000-0000-0000-000000000002', 'REGISTRAR', 'Registrar', 'Student records and enrollment administration.'),
    ('00000000-0000-0000-0000-000000000003', 'ACADEMIC_ADMIN', 'Academic administrator', 'Academic structure and curriculum administration.'),
    ('00000000-0000-0000-0000-000000000004', 'FACULTY', 'Faculty', 'Teaching and grading workflows.'),
    ('00000000-0000-0000-0000-000000000005', 'ADVISER', 'Adviser', 'Advising and student-success workflows.'),
    ('00000000-0000-0000-0000-000000000006', 'STUDENT', 'Student', 'Student self-service workflows.'),
    ('00000000-0000-0000-0000-000000000007', 'AUDITOR', 'Auditor', 'Read-only compliance and audit workflows.');

INSERT INTO app_permission (id, code, description) VALUES
    ('10000000-0000-0000-0000-000000000001', 'identity.users.read', 'Read user identity and access summaries.'),
    ('10000000-0000-0000-0000-000000000002', 'identity.users.manage', 'Create users and manage account status.'),
    ('10000000-0000-0000-0000-000000000003', 'identity.roles.manage', 'Assign or remove user roles.'),
    ('10000000-0000-0000-0000-000000000004', 'audit.events.read', 'Read security and business audit events.');

INSERT INTO app_role_permission (role_id, permission_id)
SELECT '00000000-0000-0000-0000-000000000001'::uuid, id
FROM app_permission;

INSERT INTO app_role_permission (role_id, permission_id) VALUES
    ('00000000-0000-0000-0000-000000000002', '10000000-0000-0000-0000-000000000001'),
    ('00000000-0000-0000-0000-000000000007', '10000000-0000-0000-0000-000000000004');

UPDATE app_metadata
SET metadata_value = 'identity', updated_at = CURRENT_TIMESTAMP
WHERE metadata_key = 'schema_version';
